#!/bin/bash

PHP_CONTAINER="php"
DOCKER_COMPOSE='docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml'

function usage {
    cat <<EOF
Usage:
  $0 [command]

Available commands:
  info                      Some information :D
  start                     Start docker environment
  stop                      Stop docker
  test                      Execute unit tests
  autoload                  Execute composer dump-autoload
  composer *                Execute composer command in container
EOF
    exit 1
}

function run_in_container() {
    docker exec -it $PHP_CONTAINER sh -c "$*"
}

case $1 in
    "start")
#        php -S localhost:$RUNNING_PORT -t public
        $DOCKER_COMPOSE up -d
    ;;
    "rebuild")
        $DOCKER_COMPOSE build
    ;;
    "ps")
        $DOCKER_COMPOSE ps
    ;;
    "logs")
        $DOCKER_COMPOSE logs -f
    ;;
    "info")
        run_in_container php --version
    ;;
    "stop")
        $DOCKER_COMPOSE down
    ;;
    "test")
        run_in_container vendor/bin/phpunit -vvv "${@:2}"
    ;;
    "autoload")
        run_in_container composer dump-autoload
    ;;
    "composer")
        run_in_container composer ${*:2}
    ;;
    "console")
        run_in_container php bin/console ${*:2}
    ;;
    *)
        if [ $# -eq 1 ]
        then
            $0 | grep $1
        else
            usage
        fi
   ;;
esac
