version: '3'

services:
  database:
    build:
      context: ./database
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${VAR_DIR}/data/mysql:/var/lib/mysql
    networks:
      - blog_net

  php:
    build:
      context: ./php-fpm
    container_name: php
    hostname: php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.6.4
    networks:
      - blog_net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ${VAR_DIR}/log/nginx:/var/log/nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - blog_net

networks:
  blog_net:
    ipam:
      driver: default


